# Generated by Django 3.2.25 on 2024-10-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
    ]
